In [1]:
import numpy as np
from sklearn.decomposition import NMF
import pandas as pd
import random

In [2]:
ratings = pd.read_csv('ratings.csv')

In [3]:
ratings

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [4]:
movies = pd.read_csv('movies.csv')

In [5]:
moviesIdlist=movies['movieId'].tolist()

In [6]:
MOVIES = [x[:-7] for x in (pd.read_csv('movies.csv'))['title'].values.tolist()]

In [7]:
MOVIES

['Toy Story',
 'Jumanji',
 'Grumpier Old Men',
 'Waiting to Exhale',
 'Father of the Bride Part II',
 'Heat',
 'Sabrina',
 'Tom and Huck',
 'Sudden Death',
 'GoldenEye',
 'American President, The',
 'Dracula: Dead and Loving It',
 'Balto',
 'Nixon',
 'Cutthroat Island',
 'Casino',
 'Sense and Sensibility',
 'Four Rooms',
 'Ace Ventura: When Nature Calls',
 'Money Train',
 'Get Shorty',
 'Copycat',
 'Assassins',
 'Powder',
 'Leaving Las Vegas',
 'Othello',
 'Now and Then',
 'Persuasion',
 'City of Lost Children, The (Cité des enfants perdus, La)',
 'Shanghai Triad (Yao a yao yao dao waipo qiao)',
 'Dangerous Minds',
 'Twelve Monkeys (a.k.a. 12 Monkeys)',
 'Babe',
 'Dead Man Walking',
 'It Takes Two',
 'Clueless',
 'Cry, the Beloved Country',
 'Richard III',
 'Dead Presidents',
 'Restoration',
 'Mortal Kombat',
 'To Die For',
 'How to Make an American Quilt',
 'Seven (a.k.a. Se7en)',
 'Pocahontas',
 'When Night Is Falling',
 'Usual Suspects, The',
 'Mighty Aphrodite',
 'Lamerica',
 'Big Green, The',
 'Georgia',
 'Home for the Holidays',
 'Postman, The (Postino, Il)',
 'Indian in the Cupboard, The',
 'Eye for an Eye',
 "Mr. Holland's Opus",
 "Don't Be a Menace to South Central While Drinking Your Juice in the Hood",
 'Two if by Sea',
 'Bio-Dome',
 'Lawnmower Man 2: Beyond Cyberspace',
 'French Twist (Gazon maudit)',
 'Friday',
 'From Dusk Till Dawn',
 'Fair Game',
 'Kicking and Screaming',
 'Misérables, Les',
 'Bed of Roses',
 'Big Bully',
 'Screamers',
 'Nico Icon',
 'Crossing Guard, The',
 'Juror, The',
 'White Balloon, The (Badkonake sefid)',
 "Things to Do in Denver When You're Dead",
 "Antonia's Line (Antonia)",
 'Once Upon a Time... When We Were Colored',
 'Angels and Insects',
 'White Squall',
 'Dunston Checks In',
 'Black Sheep',
 'Nick of Time',
 'Mary Reilly',
 'Vampire in Brooklyn',
 'Beautiful Girls',
 'Broken Arrow',
 'In the Bleak Midwinter',
 'Hate (Haine, La)',
 'Heidi Fleiss: Hollywood Madam',
 'City Hall',
 'Bottle Rocket',
 'Mr. Wrong',
 'Unforgettable',
 'Happy Gilmore',
 'Bridges of Madison County, The',
 'Nobody Loves Me (Keiner liebt mich)',
 'Muppet Treasure Island',
 'Catwalk',
 'Braveheart',
 'Taxi Driver',
 'Rumble in the Bronx (Hont faan kui)',
 'Before and After',
 'Anne Frank Remembered',
 "Young Poisoner's Handbook, The",
 'If Lucy Fell',
 'Steal Big, Steal Little',
 'Boys of St. Vincent, The',
 'Boomerang',
 'Chungking Express (Chung Hing sam lam)',
 'Flirting With Disaster',
 'NeverEnding Story III, The',
 "Jupiter's Wife",
 'Pie in the Sky',
 'Jade',
 'Down Periscope',
 'Man of the Year',
 'Up Close and Personal',
 'Birdcage, The',
 'Brothers McMullen, The',
 'Bad Boys',
 'Amazing Panda Adventure, The',
 'Basketball Diaries, The',
 'Awfully Big Adventure, An',
 'Amateur',
 'Apollo 13',
 'Rob Roy',
 'Addiction, The',
 'Batman Forever',
 'Beauty of the Day (Belle de jour)',
 'Beyond Rangoon',
 'Blue in the Face',
 'Canadian Bacon',
 'Casper',
 'Clockers',
 'Congo',
 'Crimson Tide',
 'Crumb',
 'Desperado',
 'Devil in a Blue Dress',
 'Die Hard: With a Vengeance',
 'Doom Generation, The',
 'First Knight',
 'Free Willy 2: The Adventure Home',
 'Hackers',
 'Jeffrey',
 'Johnny Mnemonic',
 'Judge Dredd',
 'Jury Duty',
 'Kids',
 'Living in Oblivion',
 'Lord of Illusions',
 'Love & Human Remains',
 'Mad Love',
 'Mallrats',
 'Mighty Morphin Power Rangers: The Movie',
 'Mute Witness',
 'Nadja',
 'Net, The',
 'Nine Months',
 'Party Girl',
 'Prophecy, The',
 'Reckless',
 'Safe',
 'Scarlet Letter, The',
 'Showgirls',
 'Smoke',
 'Something to Talk About',
 'Species',
 'Strange Days',
 'Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les)',
 'Three Wishes',
 'Total Eclipse',
 'To Wong Foo, Thanks for Everything! Julie Newmar',
 'Under Siege 2: Dark Territory',
 'Unstrung Heroes',
 'Unzipped',
 'Walk in the Clouds, A',
 'Waterworld',
 "White Man's Burden",
 'Wild Bill',
 'Browning Version, The',
 'Bushwhacked',
 'Burnt by the Sun (Utomlyonnye solntsem)',
 'Before the Rain (Pred dozhdot)',
 'Before Sunrise',
 'Billy Madison',
 'Babysitter, The',
 'Boys on the Side',
 'Cure, The',
 'Castle Freak',
 'Circle of Friends',
 'Clerks',
 'Don Juan DeMarco',
 'Disclosure',
 'Drop Zone',
 'Destiny Turns on the Radio',
 'Death and the Maiden',
 'Dolores Claiborne',
 'Dumb & Dumber (Dumb and Dumber)',
 'Eat Drink Man Woman (Yin shi nan nu)',
 'Exotica',
 'Exit to Eden',
 'Ed Wood',
 'French Kiss',
 'Forget Paris',
 'Far From Home: The Adventures of Yellow Dog',
 'Goofy Movie, A',
 'Hideaway',
 'Fluke',
 'Farinelli: il castrato',
 'Gordy',
 'Hoop Dreams',
 'Heavenly Creatures',
 'Houseguest',
 'Immortal Beloved',
 'Heavyweights (Heavy Weights)',
 'Hunted, The',
 'I.Q.',
 'Interview with the Vampire: The Vampire Chronicles',
 'Jefferson in Paris',
 'Jerky Boys, The',
 'Junior',
 'Just Cause',
 "Kid in King Arthur's Court, A",
 'Kiss of Death',
 'Star Wars: Episode IV - A New Hope',
 'Little Women',
 'Little Princess, A',
 'Ladybird Ladybird',
 'Like Water for Chocolate (Como agua para chocolate)',
 'Legends of the Fall',
 'Major Payne',
 'My Crazy Life (Mi vida loca)',
 'Love Affair',
 'Losing Isaiah',
 'Madness of King George, The',
 "Mary Shelley's Frankenstein (Frankenstein)",
 'Man of the House',
 'Mixed Nuts',
 'Milk Money',
 'Miracle on 34th Street',
 'Miami Rhapsody',
 'My Family',
 'Murder in the First',
 "Nobody's Fool",
 'Nell',
 'New Jersey Drive',
 'New York Cop (Nyû Yôku no koppu)',
 'Beyond Bedlam',
 'Nina Takes a Lover',
 'Natural Born Killers',
 'Only You',
 'Once Were Warriors',
 'Poison Ivy II',
 'Outbreak',
 'Léon: The Professional (a.k.a. The Professional) (Léon)',
 'Perez Family, The',
 "Pyromaniac's Love Story, A",
 'Pulp Fiction',
 'Pushing Hands (Tui shou)',
 'Priest',
 'Quiz Show',
 'Picture Bride (Bijo photo)',
 'Queen Margot (Reine Margot, La)',
 'Quick and the Dead, The',
 'Roommates',
 'Ready to Wear (Pret-A-Porter)',
 'Three Colors: Red (Trois couleurs: Rouge)',
 'Three Colors: Blue (Trois couleurs: Bleu)',
 'Three Colors: White (Trzy kolory: Bialy)',
 'Rent-a-Kid',
 'Relative Fear',
 'Stuart Saves His Family',
 'Swan Princess, The',
 'Secret of Roan Inish, The',
 'Specialist, The',
 'Stargate',
 'Santa Clause, The',
 'Shawshank Redemption, The',
 'Shallow Grave',
 'Suture',
 'Strawberry and Chocolate (Fresa y chocolate)',
 'Swimming with Sharks',
 'Sum of Us, The',
 "National Lampoon's Senior Trip",
 'To Live (Huozhe)',
 'Tank Girl',
 'Tales from the Crypt Presents: Demon Knight',
 'Star Trek: Generations',
 'Tales from the Hood',
 'Tom & Viv',
 'Village of the Damned',
 'Tommy Boy',
 'Vanya on 42nd Street',
 'Underneath',
 'Walking Dead, The',
 "What's Eating Gilbert Grape",
 'Virtuosity',
 'While You Were Sleeping',
 'War, The',
 'Double Happiness',
 "Muriel's Wedding",
 'Baby-Sitters Club, The',
 'Ace Ventura: Pet Detective',
 'Adventures of Priscilla, Queen of the Desert, The',
 'Backbeat',
 'Bitter Moon',
 'Bullets Over Broadway',
 'Clear and Present Danger',
 'Client, The',
 'Corrina, Corrina',
 'Crooklyn',
 'Crow, The',
 'Cobb',
 'Flintstones, The',
 'Forrest Gump',
 'Four Weddings and a Funeral',
 'Higher Learning',
 'I Like It Like That',
 'I Love Trouble',
 'It Could Happen to You',
 'Jungle Book, The',
 'Wonderful, Horrible Life of Leni Riefenstahl, The (Macht der Bilder: Leni Riefenstahl, Die)',
 'Lion King, The',
 'Little Buddha',
 "Wes Craven's New Nightmare (Nightmare on Elm Street Part 7: Freddy's Finale, A)",
 'Mask, The',
 'Maverick',
 'Mrs. Parker and the Vicious Circle',
 'Naked Gun 33 1/3: The Final Insult',
 'Paper, The',
 'Reality Bites',
 'Red Rock West',
 'Richie Rich',
 'River Wild, The',
 'Speed',
 'Speechless',
 'Timecop',
 'True Lies',
 'When a Man Loves a Woman',
 'Wolf',
 'Wyatt Earp',
 'Bad Company',
 'Man of No Importance, A',
 'S.F.W.',
 'Low Down Dirty Shame, A',
 'Boys Life',
 'Colonel Chabert, Le',
 'Faster Pussycat! Kill! Kill!',
 "Jason's Lyric",
 'Street Fighter',
 'Highlander III: The Sorcerer (a.k.a. Highlander: The Final Dimension)',
 'Federal Hill',
 'In the Mouth of Madness',
 '8 Seconds',
 'Above the Rim',
 'Addams Family Values',
 'Age of Innocence, The',
 'Airheads',
 'Air Up There, The',
 'Another Stakeout',
 'Bad Girls',
 'Barcelona',
 'Being Human',
 'Beverly Hillbillies, The',
 'Beverly Hills Cop III',
 'Black Beauty',
 'Blink',
 'Blown Away',
 'Blue Chips',
 'Blue Sky',
 'Body Snatchers',
 'Boxing Helena',
 'Bronx Tale, A',
 'Cabin Boy',
 'Calendar Girl',
 "Carlito's Way",
 "City Slickers II: The Legend of Curly's Gold",
 'Clean Slate',
 'Cliffhanger',
 'Coneheads',
 'Color of Night',
 'Cops and Robbersons',
 'Cowboy Way, The',
 'Dave',
 'Dazed and Confused',
 'Demolition Man',
 'Even Cowgirls Get the Blues',
 'Fatal Instinct',
 'Farewell My Concubine (Ba wang bie ji)',
 'Fearless',
 'Fear of a Black Hat',
 'With Honors',
 'Flesh and Bone',
 "Widows' Peak",
 'For Love or Money',
 'Firm, The',
 'Free Willy',
 'Fresh',
 'Fugitive, The',
 'Geronimo: An American Legend',
 'Getaway, The',
 'Getting Even with Dad',
 'Go Fish',
 'Hard Target',
 'Hot Shots! Part Deux',
 'Live Nude Girls',
 'Englishman Who Went Up a Hill But Came Down a Mountain, The',
 'House of the Spirits, The',
 'House Party 3',
 'Hudsucker Proxy, The',
 "I'll Do Anything",
 'In the Army Now',
 'In the Line of Fire',
 'In the Name of the Father',
 'Inkwell, The',
 "What's Love Got to Do with It?",
 'Jimmy Hollywood',
 'Judgment Night',
 'Jurassic Park',
 'Kalifornia',
 'Killing Zoe',
 'Lassie',
 'Last Action Hero',
 'Life with Mikey',
 'Lightning Jack',
 'M. Butterfly',
 'Made in America',
 'Malice',
 'Man Without a Face, The',
 'Manhattan Murder Mystery',
 'Menace II Society',
 'Executive Decision',
 'In the Realm of the Senses (Ai no corrida)',
 'What Happened Was...',
 'Much Ado About Nothing',
 'Mr. Wonderful',
 'Mrs. Doubtfire',
 'Naked',
 'Next Karate Kid, The',
 'No Escape',
 'North',
 'Orlando',
 'Perfect World, A',
 'Philadelphia',
 'Piano, The',
 'Poetic Justice',
 'Program, The',
 'Puppet Masters, The',
 'Radioland Murders',
 'Ref, The',
 'Remains of the Day, The',
 'Renaissance Man',
 'Rising Sun',
 'Road to Wellville, The',
 'RoboCop 3',
 'Robin Hood: Men in Tights',
 'Romeo Is Bleeding',
 'Romper Stomper',
 'Ruby in Paradise',
 'Rudy',
 'Savage Nights (Nuits fauves, Les)',
 "Schindler's List",
 'Scout, The',
 'Searching for Bobby Fischer',
 'Secret Garden, The',
 'Serial Mom',
 'Shadow, The',
 'Shadowlands',
 'Short Cuts',
 'Simple Twist of Fate, A',
 'Sirens',
 'Six Degrees of Separation',
 'Sleepless in Seattle',
 'Sliver',
 'Blade Runner',
 'Son in Law',
 'So I Married an Axe Murderer',
 'Striking Distance',
 'Super Mario Bros.',
 'Surviving the Game',
 'Terminal Velocity',
 'Thirty-Two Short Films About Glenn Gould',
 'Threesome',
 'Nightmare Before Christmas, The',
 'Three Musketeers, The',
 'Tombstone',
 'True Romance',
 'War Room, The',
 'Pagemaster, The',
 'Welcome to the Dollhouse',
 'Germinal',
 'Chasers',
 'Kika',
 'Bhaji on the Beach',
 'Little Big League',
 'Ciao, Professore! (Io speriamo che me la cavo)',
 'Spanking the Monkey',
 'Little Rascals, The',
 'Andre',
 'Escort, The (Scorta, La)',
 'Princess Caraboo',
 'Celluloid Closet, The',
 'Dear Diary (Caro Diario)',
 'Brady Bunch Movie, The',
 'Home Alone',
 'Ghost',
 'Aladdin',
 'Terminator 2: Judgment Day',
 'Dances with Wolves',
 'Batman',
 'Silence of the Lambs, The',
 'Snow White and the Seven Dwarfs',
 'Beauty and the Beast',
 'Pinocchio',
 'Pretty Woman',
 'Wild Bunch, The',
 'Love and a .45',
 'Great Day in Harlem, A',
 'One Fine Day',
 'Candyman: Farewell to the Flesh',
 'Fargo',
 'Homeward Bound II: Lost in San Francisco',
 'Heavy Metal',
 'Hellraiser: Bloodline',
 'Pallbearer, The',
 'Jane Eyre',
 'Bread and Chocolate (Pane e cioccolata)',
 'Aristocats, The',
 'Flower of My Secret, The (La flor de mi secreto)',
 'Two Much',
 'Ed',
 'Thin Line Between Love and Hate, A',
 'Last Supper, The',
 'Primal Fear',
 'All Dogs Go to Heaven 2',
 'Land and Freedom (Tierra y libertad)',
 'Denise Calls Up',
 'Theodore Rex',
 'Family Thing, A',
 'Frisk',
 'Sgt. Bilko',
 'Jack and Sarah',
 'Girl 6',
 'Diabolique',
 'Nelly & Monsieur Arnaud',
 'Courage Under Fire',
 'Mission: Impossible',
 'Cold Fever (Á köldum klaka)',
 'Moll Flanders',
 'Dragonheart',
 'Eddie',
 'James and the Giant Peach',
 'Fear',
 'Kids in the Hall: Brain Candy',
 'Underground',
 'Bloodsport 2 (a.k.a. Bloodsport II: The Next Kumite)',
 'Song of the Little Road (Pather Panchali)',
 'World of Apu, The (Apur Sansar)',
 'Mystery Science Theater 3000: The Movie',
 'Space Jam',
 'Barbarella',
 'Some Folks Call It a Sling Blade',
 'Run of the Country, The',
 'Alphaville (Alphaville, une étrange aventure de Lemmy Caution)',
 "It's My Party",
 'Operation Dumbo Drop',
 'Mrs. Winterbourne',
 'Solo',
 'Substitute, The',
 'True Crime',
 'Feeling Minnesota',
 'Delta of Venus',
 'Angus',
 'Boys',
 'Quest, The',
 'Sunset Park',
 'Mulholland Falls',
 'Truth About Cats & Dogs, The',
 'Oliver & Company',
 'Celtic Pride',
 'Flipper',
 'Dead Man',
 'Horseman on the Roof, The (Hussard sur le toit, Le)',
 'Visitors, The (Visiteurs, Les)',
 'Multiplicity',
 'Wallace & Gromit: The Best of Aardman Animation',
 'Haunted World of Edward D. Wood Jr., The',
 'Craft, The',
 'Great White Hype, The',
 'Last Dance',
 'Cold Comfort Farm',
 "Heaven's Prisoners",
 'Rock, The',
 'Cemetery Man (Dellamorte Dellamore)',
 'Twister',
 'Barb Wire',
 'Ghost in the Shell (Kôkaku kidôtai)',
 'Thinner',
 'Spy Hard',
 'Wallace & Gromit: A Close Shave',
 'Stupids, The',
 'Arrival, The',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
 'Ashes of Time (Dung che sai duk)',
 'Maya Lin: A Strong Clear Vision',
 'Stalingrad',
 'Phantom, The',
 'Striptease',
 'Heavy',
 'Jack',
 'I Shot Andy Warhol',
 'Touki Bouki',
 'Spirits of the Dead',
 'Trainspotting',
 "'Til There Was You",
 'Independence Day (a.k.a. ID4)',
 'Stealing Beauty',
 'Fan, The',
 'Hunchback of Notre Dame, The',
 'Cable Guy, The',
 'Kingpin',
 'Eraser',
 'Nutty Professor, The',
 'Unforgettable Summer, An (Un été inoubliable)',
 'Last Klezmer: Leopold Kozlowski, His Life and Music, The',
 'Somebody to Love',
 'Daylight',
 'Frighteners, The',
 'Lone Star',
 'Harriet the Spy',
 'Phenomenon',
 'Walking and Talking',
 "She's the One",
 'Time to Kill, A',
 'American Buffalo',
 'Alaska',
 'Fled',
 'Kazaam',
 'Larger Than Life',
 'Very Brady Sequel, A',
 'Collector, The (La collectionneuse)',
 'Kaspar Hauser',
 'Adventures of Pinocchio, The',
 "Joe's Apartment",
 'First Wives Club, The',
 'Ransom',
 'High School High',
 'Foxfire',
 'Chain Reaction',
 'Matilda',
 'Emma',
 'Crow: City of Angels, The',
 'House Arrest',
 'Eyes Without a Face (Yeux sans visage, Les)',
 'Tales from the Crypt Presents: Bordello of Blood',
 'Spitfire Grill, The',
 'Escape from L.A.',
 'Basquiat',
 'Tin Cup',
 'Godfather, The',
 'Supercop (Police Story 3: Supercop) (Jing cha gu shi III: Chao ji jing cha)',
 'Bound',
 'Carpool',
 'Kansas City',
 "Gone Fishin'",
 'Nothing to Lose',
 'Supercop 2 (Project S) (Chao ji ji hua)',
 'Relic, The',
 'Island of Dr. Moreau, The',
 'First Kid',
 'Trigger Effect, The',
 'Bogus',
 'Bulletproof',
 'Land Before Time III: The Time of the Great Giving',
 '1-900 (06)',
 'Halloween: The Curse of Michael Myers (Halloween 6: The Curse of Michael Myers)',
 'Twelfth Night',
 'Mother Night',
 'Wild Reeds (Les roseaux sauvages)',
 'For Whom the Bell Tolls',
 'Philadelphia Story, The',
 "Singin' in the Rain",
 'American in Paris, An',
 'Funny Face',
 "Breakfast at Tiffany's",
 'Vertigo',
 'Rear Window',
 'It Happened One Night',
 'Gaslight',
 'Gay Divorcee, The',
 'North by Northwest',
 'Apartment, The',
 'Some Like It Hot',
 'Charade',
 'Casablanca',
 'Maltese Falcon, The',
 'My Fair Lady',
 'Sabrina',
 'Roman Holiday',
 'Little Princess, The',
 'Meet Me in St. Louis',
 'Wizard of Oz, The',
 'Gone with the Wind',
 'My Favorite Year',
 'Sunset Blvd. (a.k.a. Sunset Boulevard)',
 'Citizen Kane',
 '2001: A Space Odyssey',
 'All About Eve',
 'Women, The',
 'Rebecca',
 'Foreign Correspondent',
 'Notorious',
 'Spellbound',
 'Affair to Remember, An',
 'To Catch a Thief',
 'Father of the Bride',
 'Band Wagon, The',
 'Ninotchka',
 'Love in the Afternoon',
 'Gigi',
 'Adventures of Robin Hood, The',
 'Mark of Zorro, The',
 'Laura',
 'Ghost and Mrs. Muir, The',
 'Lost Horizon',
 'Top Hat',
 'To Be or Not to Be',
 'My Man Godfrey',
 'Giant',
 'East of Eden',
 'Thin Man, The',
 'His Girl Friday',
 'Around the World in 80 Days',
 "It's a Wonderful Life",
 'Mr. Smith Goes to Washington',
 'Bringing Up Baby',
 'Penny Serenade',
 'Of Human Bondage',
 'Little Lord Fauntleroy',
 'Inspector General, The',
 '39 Steps, The',
 'Night of the Living Dead',
 'African Queen, The',
 'Beat the Devil',
 'Cat on a Hot Tin Roof',
 'Meet John Doe',
 'Farewell to Arms, A',
 'Nothing Personal',
 'Dangerous Ground',
 'Picnic',
 'Pompatus of Love, The',
 'Fly Away Home',
 'Bliss',
 'Grace of My Heart',
 'Maximum Risk',
 'Michael Collins',
 'Infinity',
 'Big Night',
 'Last Man Standing',
 'Set It Off',
 '2 Days in the Valley',
 'Extreme Measures',
 'Glimmer Man, The',
 'D3: The Mighty Ducks',
 'Chamber, The',
 'Apple Dumpling Gang, The',
 'Davy Crockett, King of the Wild Frontier',
 'Escape to Witch Mountain',
 'Love Bug, The',
 'Herbie Rides Again',
 'Old Yeller',
 'Parent Trap, The',
 'Pollyanna',
 'Homeward Bound: The Incredible Journey',
 'Shaggy Dog, The',
 'Swiss Family Robinson',
 'That Darn Cat!',
 '20,000 Leagues Under the Sea',
 'Cool Runnings',
 'Angels in the Outfield',
 'Cinderella',
 'Winnie the Pooh and the Blustery Day',
 'Three Caballeros, The',
 'Sword in the Stone, The',
 'Robin Hood: Prince of Thieves',
 'Mary Poppins',
 'Dumbo',
 "Pete's Dragon",
 'Bedknobs and Broomsticks',
 'Alice in Wonderland',
 'Fox and the Hound, The',
 'Freeway',
 'Sound of Music, The',
 'Die Hard',
 'Lawnmower Man, The',
 'Secret Agent, The',
 'Secrets & Lies',
 'That Thing You Do!',
 'To Gillian on Her 37th Birthday',
 'Beautiful Thing',
 'Long Kiss Goodnight, The',
 'Ghost and the Darkness, The',
 'Looking for Richard',
 'Trees Lounge',
 'Normal Life',
 'Get on the Bus',
 'Shadow Conspiracy',
 'Jude',
 'Everyone Says I Love You',
 "William Shakespeare's Romeo + Juliet",
 'Swingers',
 'Sleepers',
 'Aladdin and the King of Thieves',
 'Shall We Dance',
 'Crossfire',
 'Willy Wonka & the Chocolate Factory',
 'Innocents, The',
 'Sleeper',
 'Bananas',
 'Fish Called Wanda, A',
 "Monty Python's Life of Brian",
 'Victor/Victoria',
 'Candidate, The',
 'Great Race, The',
 'Bonnie and Clyde',
 'Old Man and the Sea, The',
 'Dial M for Murder',
 'Dirty Dancing',
 'Reservoir Dogs',
 'Platoon',
 "Weekend at Bernie's",
 'Basic Instinct',
 'Doors, The',
 'Crying Game, The',
 'Glengarry Glen Ross',
 "Sophie's Choice",
 'E.T. the Extra-Terrestrial',
 'Christmas Carol, A',
 'Days of Thunder',
 'Top Gun',
 'Rebel Without a Cause',
 'Streetcar Named Desire, A',
 'Children of the Corn IV: The Gathering',
 'Loser',
 "Microcosmos (Microcosmos: Le peuple de l'herbe)",
 'Palookaville',
 'Funeral, The',
 'Single Girl, A (Fille seule, La)',
 'Eighth Day, The (Huitième jour, Le)',
 'Drunks',
 'People vs. Larry Flynt, The',
 'Glory Daze',
 'Perfect Candidate, A',
 'On Golden Pond',
 'Return of the Pink Panther, The',
 'Drop Dead Fred',
 'Abyss, The',
 'Fog, The',
 'Escape from New York',
 'Howling, The',
 'Jean de Florette',
 'Manon of the Spring (Manon des sources)',
 'Private Benjamin',
 'Monty Python and the Holy Grail',
 'Hustler White',
 'Entertaining Angels: The Dorothy Day Story',
 'Line King: The Al Hirschfeld Story, The',
 'When We Were Kings',
 'Wallace & Gromit: The Wrong Trousers',
 'Return of Martin Guerre, The (Retour de Martin Guerre, Le)',
 'Lesson Faust',
 'Children Are Watching Us, The (Bambini ci guardano, I)',
 'Tin Drum, The (Blechtrommel, Die)',
 'Ruling Class, The',
 'Mina Tannenbaum',
 'Dear God',
 'Best of the Best 3: No Turning Back',
 'Bob Roberts',
 'Cinema Paradiso (Nuovo cinema Paradiso)',
 'Cook the Thief His Wife & Her Lover, The',

In [8]:
MOVIEID = [x for x in (pd.read_csv('movies.csv'))['movieId'].values.tolist()]

In [9]:
len(MOVIES)

9742

In [10]:
len(MOVIEID)

9742

In [11]:
#MOVIES = list(dict.fromkeys(MOVIES))
#len(MOVIES)

In [12]:
movies['title'] = MOVIES

In [13]:
movies

,movieId,title,genres
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji,Adventure|Children|Fantasy
2,3,Grumpier Old Men,Comedy|Romance
3,4,Waiting to Exhale,Comedy|Drama|Romance
4,5,Father of the Bride Part II,Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic,Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero,Animation|Comedy|Fantasy
9739,193585,Flint,Drama
9740,193587,Bungo Stray Dogs: Dead Apple,Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules,Comedy

In [14]:
len(movies)

9742

In [15]:
ratings2=ratings.set_index(['userId'])

In [16]:
ratings3 = ratings.drop(['timestamp'], axis=1)

In [17]:
ratings3

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [18]:
len(ratings3)

100836

In [19]:
newmoviesratings = pd.merge(ratings3, movies, on='movieId')

In [20]:
newmoviesratings

,userId,movieId,rating,title,genres
0,1,1,4.0,Toy Story,Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,Toy Story,Adventure|Animation|Children|Comedy|Fantasy
2,7,1,4.5,Toy Story,Adventure|Animation|Children|Comedy|Fantasy
3,15,1,2.5,Toy Story,Adventure|Animation|Children|Comedy|Fantasy
4,17,1,4.5,Toy Story,Adventure|Animation|Children|Comedy|Fantasy
...,...,...,...,...,...
100831,610,160341,2.5,Bloodmoon,Action|Thriller
100832,610,160527,4.5,Sympathy for the Underdog,Action|Crime|Drama
100833,610,160836,3.0,Hazard,Action|Drama|Thriller
100834,610,163937,3.5,Blair Witch,Horror|Thriller
100835,610,163981,3.5,31,Horror

In [21]:
newmoviesratings2=newmoviesratings[['userId','title','rating']]

In [22]:
newmoviesratings2

        userId                      title  rating
0            1                  Toy Story     4.0
1            5                  Toy Story     4.0
2            7                  Toy Story     4.5
3           15                  Toy Story     2.5
4           17                  Toy Story     4.5
...        ...                        ...     ...
100831     610                  Bloodmoon     2.5
100832     610  Sympathy for the Underdog     4.5
100833     610                     Hazard     3.0
100834     610                Blair Witch     3.5
100835     610                         31     3.5

[100836 rows x 3 columns]

In [23]:
newf=newmoviesratings2.set_index('userId')

In [24]:
newf

                            title  rating
userId
1                       Toy Story     4.0
5                       Toy Story     4.0
7                       Toy Story     4.5
15                      Toy Story     2.5
17                      Toy Story     4.5
...                           ...     ...
610                     Bloodmoon     2.5
610     Sympathy for the Underdog     4.5
610                        Hazard     3.0
610                   Blair Witch     3.5
610                            31     3.5

[100836 rows x 2 columns]

In [25]:
#newf = newmoviesratings2.pivot(index='userId', columns='title')

In [26]:
ratings3 = ratings.drop(['timestamp'], axis=1)

In [27]:
newf = ratings3.pivot(index='userId', columns='movieId')

In [28]:
newf

        rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10
userId
1          4.0    NaN    4.0    NaN    NaN    4.0    NaN    NaN    NaN    NaN
2          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
3          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
4          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
5          4.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
606        2.5    NaN    NaN    NaN    NaN    NaN    2.5    NaN    NaN    NaN
607        4.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
608        2.5    2.0    2.0    NaN    NaN    NaN    NaN    NaN    NaN    4.0
609        3.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    4.0
610        5.0    NaN    NaN    NaN    NaN    5.0    NaN    NaN    NaN    NaN

         ...                                                                 \
movieId  ... 193565 193567 193571 193573 193579 193581 193583 193585 193587
userId   ...
1        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
3        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
4        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
5        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
606      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
607      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
608      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
609      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
610      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN


movieId 193609
userId
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
...        ...
606        NaN
607        NaN
608        NaN
609        NaN
610        NaN

[610 rows x 9724 columns]

In [29]:
actualmovieIdslist=ratings3['movieId'].tolist()

In [30]:
#ratingsmovieIdlist=ratings['movieId'].tolist()

In [31]:
newmoviesIDlist = [x for x in moviesIdlist if x in actualmovieIdslist]

In [32]:
len(newmoviesIDlist)

9724

In [33]:
newf2=newf.fillna(3.000000)

In [34]:
newf2

        rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10
userId
1          4.0    3.0    4.0    3.0    3.0    4.0    3.0    3.0    3.0    3.0
2          3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
3          3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
4          3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
5          4.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
606        2.5    3.0    3.0    3.0    3.0    3.0    2.5    3.0    3.0    3.0
607        4.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
608        2.5    2.0    2.0    3.0    3.0    3.0    3.0    3.0    3.0    4.0
609        3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    4.0
610        5.0    3.0    3.0    3.0    3.0    5.0    3.0    3.0    3.0    3.0

         ...                                                                 \
movieId  ... 193565 193567 193571 193573 193579 193581 193583 193585 193587
userId   ...
1        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
2        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
3        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
4        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
5        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
606      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
607      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
608      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
609      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0
610      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0


movieId 193609
userId
1          3.0
2          3.0
3          3.0
4          3.0
5          3.0
...        ...
606        3.0
607        3.0
608        3.0
609        3.0
610        3.0

[610 rows x 9724 columns]

In [35]:
R=newf2.values

In [36]:
R

array([[4. , 3. , 4. , ..., 3. , 3. , 3. ],
       [3. , 3. , 3. , ..., 3. , 3. , 3. ],
       [3. , 3. , 3. , ..., 3. , 3. , 3. ],
       ...,
       [2.5, 2. , 2. , ..., 3. , 3. , 3. ],
       [3. , 3. , 3. , ..., 3. , 3. , 3. ],
       [5. , 3. , 3. , ..., 3. , 3. , 3. ]])

In [37]:
model = NMF(n_components=10, init='random', random_state=10)

In [38]:
model.fit(R)

NMF(alpha=0.0, beta_loss='frobenius', init='random', l1_ratio=0.0, max_iter=200,
    n_components=10, random_state=10, shuffle=False, solver='cd', tol=0.0001,
    verbose=0)

In [39]:
Q = model.components_  # movie-genre matrix

In [40]:
P = model.transform(R)  # user-genre matrix

In [41]:
print(model.reconstruction_err_)

331.7643512500957

In [42]:
nR = np.dot(P, Q)

In [43]:
nR

array([[3.85334815, 3.23929205, 3.13316885, ..., 3.00139387, 3.00351925,
        2.9891991 ],
       [3.1300499 , 3.01321034, 2.99438994, ..., 3.00257888, 3.00342496,
        3.00439365],
       [3.0503099 , 3.0147466 , 2.95610635, ..., 3.00132832, 2.99424463,
        2.98655487],
       ...,
       [3.34534593, 3.1380288 , 2.78720652, ..., 2.9785765 , 2.97658175,
        2.99924344],
       [3.18420646, 3.04170505, 3.00418841, ..., 3.00140675, 3.00088641,
        3.00066233],
       [3.70978537, 3.19320007, 2.61052062, ..., 3.03581357, 3.00096229,
        3.07564937]])

In [44]:
len(MOVIES)

9742

In [45]:
randomuser = ['Aladdin', 'Lion King, The', 'Hercules']

In [46]:
randomratings = [5,5,5]

In [47]:
len(MOVIES)

9742

In [48]:
randomlist = [3]*len(newmoviesIDlist)

In [49]:
randomlist

[3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [50]:
index0=MOVIES.index(randomuser[0])

In [51]:
ID0=MOVIEID[index0]

In [52]:
index0b=newmoviesIDlist.index(ID0)

In [53]:
index0b

506

In [54]:
randomlist[index0b]=randomratings[0]

In [55]:
index1=MOVIES.index(randomuser[1])
ID1=MOVIEID[index1]
index1b=newmoviesIDlist.index(ID1)
randomlist[index1b]=randomratings[1]

In [56]:
index2=MOVIES.index(randomuser[2])
ID2=MOVIEID[index2]
index2b=newmoviesIDlist.index(ID2)
randomlist[index2b]=randomratings[2]

In [57]:
len(randomlist)

9724

In [58]:
nR

array([[3.85334815, 3.23929205, 3.13316885, ..., 3.00139387, 3.00351925,
        2.9891991 ],
       [3.1300499 , 3.01321034, 2.99438994, ..., 3.00257888, 3.00342496,
        3.00439365],
       [3.0503099 , 3.0147466 , 2.95610635, ..., 3.00132832, 2.99424463,
        2.98655487],
       ...,
       [3.34534593, 3.1380288 , 2.78720652, ..., 2.9785765 , 2.97658175,
        2.99924344],
       [3.18420646, 3.04170505, 3.00418841, ..., 3.00140675, 3.00088641,
        3.00066233],
       [3.70978537, 3.19320007, 2.61052062, ..., 3.03581357, 3.00096229,
        3.07564937]])

In [59]:
ratings3

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [60]:
ratings4 = ratings3.groupby('userId')

In [61]:
maxValue = ratings3['userId'].max()

In [62]:
maxValue

610

In [63]:
newUserID=maxValue+1

In [64]:
newUserID

611

In [65]:
array3=np.array(randomlist)

In [66]:
array3

array([3, 3, 3, ..., 3, 3, 3])

In [67]:
array3=array3.reshape(1,-1)

In [68]:
#model.fit(R)

In [69]:
P = model.transform(array3)

In [70]:
P

array([[1.65003946, 0.87183689, 0.5963215 , 0.54059965, 0.51781286,
        0.34868332, 0.53000465, 0.56719135, 0.53753869, 0.37967333]])

In [71]:
nR = np.dot(P, Q)

In [72]:
finaluser=nR[-1]

In [73]:
finaluser

array([3.19489782, 3.07042325, 3.01110418, ..., 3.00305848, 2.99999424,
       2.998227  ])

In [74]:
#len(finaluser)

In [75]:
#newuserrow=[newUserID]+randomlist

In [76]:
#newuserrow

In [77]:
#newf3=newuserrow.append(newf2)

In [78]:
#newf3

In [79]:
R

In [80]:
R2=R.tolist()

In [81]:
R2[0]

In [82]:
R3 = R2 + [randomlist]

In [83]:
R3

In [84]:
R3[-1]

In [85]:
R4=np.array(R3)

In [86]:
R4

In [87]:
model.fit(R4)

In [88]:
Q = model.components_

In [89]:
P = model.transform(R4)

In [90]:
nR = np.dot(P, Q)

In [91]:
nR

array([[3.19489782, 3.07042325, 3.01110418, ..., 3.00305848, 2.99999424,
        2.998227  ]])

In [92]:
finalList=nR.tolist()

In [93]:
totalratingsnewuser=finalList[-1]

In [94]:
len(totalratingsnewuser)

9724

In [95]:
len(newmoviesIDlist)

9724

In [96]:
#index1=MOVIES.index(randomuser[1])
#ID1=MOVIEID[index1]
#index1b=newmoviesIDlist.index(ID1)
#randomlist[index1b]=randomratings[1]

In [97]:
finalDf1 = pd.DataFrame(
    {'movieid': newmoviesIDlist,
     'ratingsnewuser': totalratingsnewuser
    })

In [98]:
finalDf1

      movieid  ratingsnewuser
0           1        3.194898
1           2        3.070423
2           3        3.011104
3           4        2.992578
4           5        3.028354
...       ...             ...
9719   193581        3.000223
9720   193583        3.001312
9721   193585        3.003058
9722   193587        2.999994
9723   193609        2.998227

[9724 rows x 2 columns]

In [99]:
finalDf2 = pd.DataFrame(
    {'title': MOVIES,
     'movieid': MOVIEID,
    })

In [100]:
finalDf2

                                   title  movieid
0                              Toy Story        1
1                                Jumanji        2
2                       Grumpier Old Men        3
3                      Waiting to Exhale        4
4            Father of the Bride Part II        5
...                                  ...      ...
9737  Black Butler: Book of the Atlantic   193581
9738               No Game No Life: Zero   193583
9739                               Flint   193585
9740        Bungo Stray Dogs: Dead Apple   193587
9741        Andrew Dice Clay: Dice Rules   193609

[9742 rows x 2 columns]

In [101]:
finalDf3=finalDf2.drop_duplicates()

In [102]:
finalDf3

                                   title  movieid
0                              Toy Story        1
1                                Jumanji        2
2                       Grumpier Old Men        3
3                      Waiting to Exhale        4
4            Father of the Bride Part II        5
...                                  ...      ...
9737  Black Butler: Book of the Atlantic   193581
9738               No Game No Life: Zero   193583
9739                               Flint   193585
9740        Bungo Stray Dogs: Dead Apple   193587
9741        Andrew Dice Clay: Dice Rules   193609

[9742 rows x 2 columns]

In [103]:
finaldf4 = pd.merge(finalDf3, finalDf1, on='movieid')

In [104]:
finaldf5=finaldf4.dropna()

In [105]:
finaldf5

                                   title  movieid  ratingsnewuser
0                              Toy Story        1        3.194898
1                                Jumanji        2        3.070423
2                       Grumpier Old Men        3        3.011104
3                      Waiting to Exhale        4        2.992578
4            Father of the Bride Part II        5        3.028354
...                                  ...      ...             ...
9719  Black Butler: Book of the Atlantic   193581        3.000223
9720               No Game No Life: Zero   193583        3.001312
9721                               Flint   193585        3.003058
9722        Bungo Stray Dogs: Dead Apple   193587        2.999994
9723        Andrew Dice Clay: Dice Rules   193609        2.998227

[9724 rows x 3 columns]

In [106]:
finaldf6=finaldf5.sort_values('ratingsnewuser', ascending=False)

In [107]:
finalmovielist=finaldf6['title'].tolist()

In [108]:
finalmovielist

['Shawshank Redemption, The',
 'Forrest Gump',
 'Pulp Fiction',
 'Silence of the Lambs, The',
 'Braveheart',
 'Apollo 13',
 'Star Wars: Episode IV - A New Hope',
 "Schindler's List",
 'Fugitive, The',
 'Matrix, The',
 'Terminator 2: Judgment Day',
 'Jurassic Park',
 'Toy Story',
 'Lion King, The',
 'Aladdin',
 'Beauty and the Beast',
 'Dances with Wolves',
 'Independence Day (a.k.a. ID4)',
 'Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark)',
 'Usual Suspects, The',
 'Speed',
 'Star Wars: Episode V - The Empire Strikes Back',
 'Twelve Monkeys (a.k.a. 12 Monkeys)',
 'Mission: Impossible',
 'Fargo',
 'Crimson Tide',
 'Clear and Present Danger',
 'Star Wars: Episode VI - Return of the Jedi',
 'Twister',
 'True Lies',
 'Saving Private Ryan',
 "Mr. Holland's Opus",
 'Star Trek: First Contact',
 'Shrek',
 'Rock, The',
 'Seven (a.k.a. Se7en)',
 'Die Hard: With a Vengeance',
 'Firm, The',
 'Ghost',
 'Fight Club',
 'Lord of the Rings: The Fellowship of the Ring, The',
 'American Beauty',
 'Sleepless in Seattle',
 'While You Were Sleeping',
 'Babe',
 'Princess Bride, The',
 'Pretty Woman',
 'Dark Knight, The',
 'Lord of the Rings: The Return of the King, The',
 'Disclosure',
 "Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone)",
 'Up',
 'Godfather, The',
 'Back to the Future',
 'Dead Man Walking',
 'Broken Arrow',
 'Lord of the Rings: The Two Towers, The',
 'Jumanji',
 'Harry Potter and the Prisoner of Azkaban',
 'Star Trek: Generations',
 'Outbreak',
 'GoldenEye',
 'Client, The',
 'Mrs. Doubtfire',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
 'Stargate',
 'American President, The',
 'Birdcage, The',
 'Blade Runner',
 'Taxi Driver',
 'Batman',
 'Titanic',
 'Gladiator',
 'Harry Potter and the Chamber of Secrets',
 'Batman Forever',
 'Mask, The',
 "One Flew Over the Cuckoo's Nest",
 'Hunchback of Notre Dame, The',
 'Eternal Sunshine of the Spotless Mind',
 'Postman, The (Postino, Il)',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'Net, The',
 'Little Women',
 "What's Eating Gilbert Grape",
 'Finding Nemo',
 'Emma',
 "Amelie (Fabuleux destin d'Amélie Poulain, Le)",
 'Willy Wonka & the Chocolate Factory',
 'X-Men',
 'Dave',
 'First Knight',
 'Phenomenon',
 'Terminator, The',
 'Interview with the Vampire: The Vampire Chronicles',
 'Men in Black (a.k.a. MIB)',
 'Snow White and the Seven Dwarfs',
 'League of Extraordinary Gentlemen, The (a.k.a. LXG)',
 'Beautiful Mind, A',
 'Tommy Boy',
 'Santa Clause, The',
 'In the Line of Fire',
 'Heat',
 'Time to Kill, A',
 'Lara Croft: Tomb Raider',
 'Sense and Sensibility',
 'Tombstone',
 'Contact',
 'Alien',
 'Harry Potter and the Goblet of Fire',
 'French Kiss',
 'Like Water for Chocolate (Como agua para chocolate)',
 'I.Q.',
 'Aliens',
 'Election',
 'Leaving Las Vegas',
 'Sound of Music, The',
 'Rumble in the Bronx (Hont faan kui)',
 'Naked Gun 33 1/3: The Final Insult',
 'Indiana Jones and the Last Crusade',
 'Happy Gilmore',
 'Piano, The',
 'Eragon',
 'Erin Brockovich',
 'Sabrina',
 'Maverick',
 'Demolition Man',
 'Young Frankenstein',
 'Clerks',
 'Ed Wood',
 'Philadelphia Story, The',
 'WALL·E',
 'Legally Blonde',
 'Harry Potter and the Half-Blood Prince',
 'Philadelphia',
 'Dragonheart',
 'Enemy of the State',
 'Monsters, Inc.',
 'Madness of King George, The',
 'Lara Croft Tomb Raider: The Cradle of Life',
 'Jaws',
 'Get Shorty',
 'Star Wars: Episode I - The Phantom Menace',
 'How to Lose a Guy in 10 Days',
 'Pocahontas',
 'Rear Window',
 'Casablanca',
 'Hoop Dreams',
 'Eraser',
 'Scary Movie',
 'Undercover Brother',
 'North by Northwest',
 'Maltese Falcon, The',
 'Jungle Book, The',
 'Gods Must Be Crazy, The',
 'Miracle on 34th Street',
 'Air Force One',
 'Life Is Beautiful (La Vita è bella)',
 'Sixth Sense, The',
 'Shanghai Noon',
 'Gone in 60 Seconds',
 'Be Cool',
 'Nell',
 'Three Musketeers, The',
 'Just Go with It',
 'Green Mile, The',
 'Good Will Hunting',
 'English Patient, The',
 'Con Air',
 'Rocketeer, The',
 'Star Trek IV: The Voyage Home',
 'Superman',
 'Island of Dr. Moreau, The',
 'Ransom',
 'Army of Darkness',
 'Toys',
 'Boot, Das (Boat, The)',
 'Blended',
 'Transformers: Dark of the Moon',
 'Father of the Bride Part II',
 'River Wild, The',
 'Billy Madison',
 'Aeon Flux',
 'Ghost and the Darkness, The',
 'Fantastic Four',
 'Cliffhanger',
 'Sweet Home Alabama',
 'Chinatown',
 'Road Warrior, The (Mad Max 2)',
 'Harry Potter and the Deathly Hallows: Part 2',
 'Quiz Show',
 'Just Cause',
 'Rambo III',
 'Next',
 'Tuxedo, The',
 'Mummy Returns, The',
 'Doctor Dolittle',
 "America's Sweethearts",
 'Blazing Saddles',
 'Congo',
 'Angel Eyes',
 'Nixon',
 'Clueless',
 'Star Trek II: The Wrath of Khan',
 'Secret of Roan Inish, The',
 'First Wives Club, The',
 '2001: A Space Odyssey',
 'Harry Potter and the Deathly Hallows: Part 1',
 'Murder in the First',
 'This Is Spinal Tap',
 'Deep Blue Sea',
 'The Intern',
 'Indian in the Cupboard, The',
 'U-571',
 'Transformers: Revenge of the Fallen',
 'Cop Out',
 'Psycho',
 'Spirited Away (Sen to Chihiro no kamikakushi)',
 'Walk in the Clouds, A',
 "King's Speech, The",
 'Jack',
 'The Imitation Game',
 'Crossroads',
 'Tomorrowland',
 'American History X',
 'Jason X',
 'Executive Decision',
 'Carnival Magic',
 'Long Kiss Goodnight, The',
 'Mummy, The',
 'Taken 3',
 'Proposal, The',
 'Core, The',
 'Bodyguard, The',
 'Ed',
 'Over the Top',
 'Love Actually',
 'Killer Shrews, The',
 'Harry Potter and the Order of the Phoenix',
 'L.A. Confidential',
 'Giant Spider Invasion, The',
 'Miss Congeniality',
 'Yongary: Monster from the Deep',
 'Ring of Terror',
 'Down to Earth',
 'AVP: Alien vs. Predator',
 '10 Things I Hate About You',
 'Avalanche',
 'Attack of the Giant Leeches',
 'The Pumaman',
 "Let's Go to Prison",
 'Arthur 2: On the Rocks',
 'Dolores Claiborne',
 'Glitter',
 'Night at the Museum',
 'Easy A',
 'Crouching Tiger, Hidden Dragon (Wo hu cang long)',
 'Heavy Metal',
 'Bone Collector, The',
 'Analyze That',
 "Dude, Where's My Car?",
 'Ice Age',
 'Close Encounters of the Third Kind',
 'Black Knight',
 'Touch of Evil',
 'Kids',
 'Halloween',
 'Doom',
 'Abyss, The',
 'Starcrash (a.k.a. Star Crash)',
 'Prince of Persia: The Sands of Time',
 'Taken 2',
 'Vacation',
 "Pirates of the Caribbean: Dead Man's Chest",
 'Big Bounce, The',
 'White Squall',
 'Chasing Liberty',
 'Wasp Woman, The',
 'Predator',
 'Step Brothers',
 'Bulletproof Monk',
 'Meet the Parents',
 'Girl, Interrupted',
 'Boys on the Side',
 '3000 Miles to Graceland',
 'City of Lost Children, The (Cité des enfants perdus, La)',
 'Grown Ups 2',
 'Friday',
 'Indestructible Man',
 'Clonus Horror, The',
 'Jerry Maguire',
 'Ernest Saves Christmas',
 'Ladies Man, The',
 'Galaxy Quest',
 'Skyline',
 'Deep Impact',
 'Coyote Ugly',
 'Avengers, The',
 'Superfast!',
 "Something's Gotta Give",
 'Musketeer, The',
 'Reptilicus',
 'Your Highness',
 'I Spy',
 'Escape from L.A.',
 'Mitchell',
 'The Scorpion King',
 'Clash of the Titans',
 'Sisters',
 "Big Momma's House",
 'Legends of the Fall',
 'Jonah Hex',
 'Tracers',
 'The Beast of Hollow Mountain',
 'To Wong Foo, Thanks for Everything! Julie Newmar',
 'Bio-Dome',
 'Searching for Bobby Fischer',
 'Matrix Reloaded, The',
 'Sitter, The',
 'My Blue Heaven',
 'Scooby-Doo',
 'Reindeer Games',
 'American Graffiti',
 'Beginning of the End',
 'Loser',
 '300: Rise of an Empire',
 'That Thing You Do!',
 'Sliding Doors',
 'Get Hard',
 'Wedding Planner, The',
 'Tangled',
 'Pitch Black',
 'View to a Kill, A',
 'Horrors of Spider Island (Ein Toter Hing im Netz)',
 'Battle: Los Angeles',
 'Oblivion',
 'Wizards of the Lost Kingdom II',
 'Incredibles, The',
 'M*A*S*H (a.k.a. MASH)',
 'When a Man Loves a Woman',
 'Kate & Leopold',
 'Michael',
 'The Face of an Angel',
 'Traffic',
 'Brazil',
 'Rise of the Guardians',
 'Remains of the Day, The',
 'Waking Ned Devine (a.k.a. Waking Ned)',
 'Just Married',
 'Wicker Man, The',
 'Thomas Crown Affair, The',
 'Four Weddings and a Funeral',
 'American Outlaws',
 'Maid in Manhattan',
 'Fantastic Four: Rise of the Silver Surfer',
 'Rush Hour 2',
 'Horrible Bosses 2',
 "Nobody's Fool",
 'Jaws 3-D',
 'Cowboys & Aliens',
 '28 Days',
 'African Queen, The',
 'Firewall',
 'Vigilante Diaries',
 'Lethal Weapon 4',
 'Knight and Day',
 'Little Princess, A',
 "Don't Tell Mom the Babysitter's Dead",
 'Hellraiser',
 "That's My Boy",
 'Rollerball',
 '50 First Dates',
 'Nacho Libre',
 'Just Before I Go',
 'Ernest Goes to Camp',
 'Cheaper by the Dozen',
 'Big Top Pee-Wee',
 'White House Down',
 "Brain That Wouldn't Die, The",
 'Precious Cargo',
 'King and I, The',
 'Persuasion',
 'Identity Thief',
 "Christmas Vacation (National Lampoon's Christmas Vacation)",
 'Big Chill, The',
 'The Boss',
 'Notebook, The',
 'Lockout',
 'Tormented',
 'Born Yesterday',
 'Calendar Girls',
 'Kalifornia',
 'Intouchables',
 'Bulletproof',
 'Wyatt Earp',
 'Camp Rock',
 'Airplane II: The Sequel',
 'Search Party',
 'Bed of Roses',
 'Seventh Son',
 'Syrup',
 'Circle of Friends',
 'Mission to Mars',
 'Dark Shadows',
 'Lake Placid',
 'Grudge, The',
 'Mighty Aphrodite',
 'Agent Cody Banks',
 'Internship, The',
 'Tourist, The',
 'Frequency',
 'Cadillac Man',
 'How to Train Your Dragon',
 'Paul',
 'Freddy Got Fingered',
 'The Boy Next Door',
 'Bubble Boy',
 'Land That Time Forgot, The',
 'Men in Black II (a.k.a. MIIB) (a.k.a. MIB 2)',
 'Down Periscope',
 'Angels and Insects',
 'Wild Horses',
 'Crow, The',
 'Screwed',
 'Wag the Dog',
 'Oscar',
 'Big Mommas: Like Father, Like Son',
 'Addams Family, The',
 'Beverly Hills Cop III',
 'Lone Star',
 'Time Machine, The',
 'Junior',
 'Dukes of Hazzard, The',
 'Wanderlust',
 'Inescapable',
 'Stick It',
 'Salt',
 'Inherit the Wind',
 'Butch Cassidy and the Sundance Kid',
 'Heavenly Creatures',
 'Forget Paris',
 'Deconstructing Harry',
 'Cocktail',
 'Dirty Dancing',
 'Third Man, The',
 'Medallion, The',
 'Assassins',
 'No Holds Barred',
 'Wrath of the Titans',
 'Sphere',
 'Jeffrey',
 'Casper',
 'Bourne Identity, The',
 'Change-Up, The',
 'Ghostbusters',
 'Van Helsing',
 'Robot Overlords',
 'Dragon: The Bruce Lee Story',
 'Colombiana',
 'Anti-Social',
 'Lost in Space',
 'Getaway',
 'Gun Shy',
 'Space Cowboys',
 'Wildcats',
 'Eight Legged Freaks',
 'Piranha 3DD (a.k.a. Piranha DD)',
 'Leonard Part 6',
 'San Andreas',
 'Mulan',
 'American Pie',
 'Must Love Dogs',
 'Smokey and the Bandit III',
 'Gentlemen Broncos',
 'Sword of Vengeance',
 'Elektra Luxx',
 'Game, The',
 'Highlander II: The Quickening',
 'Snakes on a Plane',
 "She's Out of Control",
 "Rosemary's Baby",
 'Independence Day: Resurgence',
 'Pleasantville',
 'Ben-Hur',
 'Observe and Report',
 'Homeward Bound II: Lost in San Francisco',
 'Thinner',
 'Tarzan',
 'Terminator 3: Rise of the Machines',
 'All Roads Lead to Rome',
 'Boomerang',
 'Chill Factor',
 'Help, The',
 'Infini',
 'Police Academy: Mission to Moscow',
 'Now and Then',
 'Boat Trip',
 'Apocalypse Now',
 'World War Z',
 'Keanu',
 'Rat Race',
 'Fifty Shades of Grey',
 'Hudson Hawk',
 'Evolution',
 'Batman & Robin',
 'Houseguest',
 'Up Close and Personal',
 'John Tucker Must Die',
 'Gattaca',
 'Warcraft',
 'Sgt. Bilko',
 'Seventh Seal, The (Sjunde inseglet, Det)',
 'To Die For',
 '15 Minutes',
 'Runner Runner',
 'This Island Earth',
 'Monkeybone',
 'Think Like a Man Too',
 'Henry: Portrait of a Serial Killer',
 'Exorcist, The',
 'S.W.A.T.',
 'Scary Movie 2',
 'Big Green, The',
 'My Fair Lady',
 'Strangers on a Train',
 'Being There',
 'Lifeguard, The',
 'Due Date',
 'Mona Lisa',
 'Violet & Daisy',
 'Meatballs Part II',
 'Grudge Match',
 'Manchurian Candidate, The',
 'Game Plan, The',
 'Exposed',
 'Sleeper',
 'National Treasure',
 'Harold and Maude',
 'House Bunny, The',
 'Die Hard',
 'R.I.P.D.',
 'Omen, The',
 'Destiny Turns on the Radio',
 'Blades of Glory',
 'White Noise',
 'I Now Pronounce You Chuck and Larry',
 'Around the World in 80 Days',
 'Dark Tide',
 'One for the Money',
 'The 5th Wave',
 "Charlie's Angels: Full Throttle",
 'To Catch a Thief',
 'Primal Fear',
 "The Rocky Horror Picture Show: Let's Do the Time Warp Again",
 'Face/Off',
 'Shall We Dance? (Shall We Dansu?)',
 'Tammy',
 'Freddy vs. Jason',
 'Bridge to Terabithia',
 'Hot Rod',
 'Fear',
 'Undercover Blues',
 'Body',
 'Doctor Who: The Time of the Doctor',
 'Black Sheep',
 'Clockstoppers',
 "Cheech and Chong's Up in Smoke",
 'Multiplicity',
 'Hancock',
 'Break-Up, The',
 'Howard the Duck',
 'Harold and Kumar Go to White Castle',
 'Host, The',
 'Holiday Inn',
 'Sunset Blvd. (a.k.a. Sunset Boulevard)',
 'Bonnie and Clyde',
 'Blue Velvet',
 'Wolf',
 'Truth About Cats & Dogs, The',
 'Killers',
 'Octopussy',
 'Lone Ranger, The',
 'Prime',
 'Call, The',
 'Land of the Dead',
 'Memento',
 'Runaway Bride',
 'Wild Orchid',
 'Spawn',
 '9 1/2 Weeks (Nine 1/2 Weeks)',
 'I Am Wrath',
 'Taken',
 'Made',
 'Double, The',
 'Don Juan DeMarco',
 'Hellbound: Hellraiser II',
 'Garfield: The Movie',
 'Bring It On: In It To Win It',
 "Winter's Tale",
 'Ghosts of Mars',
 'Garage Days',
 'Arthur',
 'London Boulevard',
 'Dinner for Schmucks',
 'Fantastic Four',
 'Down to You',
 '18 Again!',
 'Catch and Release',
 'Jaws: The Revenge',
 'Bring It On Again',
 'Together (Tillsammans)',
 'Woman on Top',
 'Brick Mansions',
 'Aristocrats, The',
 "Gone Fishin'",
 'Colonia',
 'Rob Roy',
 'How to Make Love to a Woman',
 'Much Ado About Nothing',
 'Lethal Weapon 3',
 'Legend of Drunken Master, The (Jui kuen II)',
 'Eve of Destruction',
 'Zombeavers',
 "Outfoxed: Rupert Murdoch's War on Journalism",
 'Screamers',
 'Last Knights',
 'Hot Pursuit',
 'Specialist, The',
 'Simon Sez',
 'Fraternity Vacation',
 'Jury Duty',
 'Dungeons & Dragons',
 '2 Fast 2 Furious (Fast and the Furious 2, The)',
 'Staten Island',
 'Why Stop Now',
 'Secret in Their Eyes',
 'Elektra',
 'Paperman',
 "Dante's Peak",
 'Herbie: Fully Loaded',
 'Iron Man',
 'Escape from the Planet of the Apes',
 'Joyful Noise',
 'No Strings Attached',
 'Something to Talk About',
 'Angels in the Outfield',
 'Flintstones, The',
 'Shining, The',
 'Bandits',
 'Red Planet',
 'Big Bully',
 'Fun with Dick and Jane',
 'Drive Hard',
 'Jungle Book, The',
 'Paper, The',
 "I'll Follow You Down",
 'Sweetest Thing, The',
 'Spider-Man 3',
 'Crumb',
 'Matrix Revolutions, The',
 'Lizzie McGuire Movie, The',
 'Fan, The',
 'The Opposite Sex',
 'Day of the Doctor, The',
 'Sharknado 3: Oh Hell No!',
 'Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The',
 "Man's Best Friend",
 'Better Living Through Chemistry',
 'Revenge of the Nerds II: Nerds in Paradise',
 'Back to the Beach',
 'Some Like It Hot',
 'Englishman Who Went Up a Hill But Came Down a Mountain, The',
 'Battleship',
 'Miss March',
 'Crocodile Dundee in Los Angeles',
 'At Middleton',
 'Bad Teacher',
 'Welcome to Happiness',
 'Children of the Corn IV: The Gathering',
 'Gone',
 'Knot, The',
 'Caveman',
 'Echelon Conspiracy',
 "Santa's Little Helper",
 'Saw III',
 'Little Voice',
 'Resident Evil: Apocalypse',
 "We're the Millers",
 'Afterglow',
 'Near Dark',
 'Sharknado 4: The 4th Awakens',
 'Burnt',
 'American Heist',
 'Fire with Fire',
 'In the Electric Mist',
 'Two Night Stand',
 'Barefoot',
 'Kicking Off',
 'Spy',
 'Bridget Jones: The Edge of Reason',
 'Lawnmower Man 2: Beyond Cyberspace',
 'Windtalkers',
 'Three Stooges, The',
 'High Noon',
 'Lola Versus',
 'Vamps',
 'Anger Management',
 'Adventures of Priscilla, Queen of the Desert, The',
 'Return to Sender',
 'Wristcutters: A Love Story',
 'Overboard',
 'Whole Ten Yards, The',
 'Conversation, The',
 'Angels & Demons',
 'Guardians of the Galaxy 2',
 'Paul Blart: Mall Cop 2',
 'Our Family Wedding',
 'Bunraku',
 'Bringing Down the House',
 'Evil Dead, The',
 'Benji',
 'Rising Sun',
 'Into the Grizzly Maze',
 '20,000 Leagues Under the Sea',
 'Revenge of the Green Dragons',
 'Half Baked',
 'Rules of Engagement',
 'Shark Night 3D',
 'Conformist, The (Conformista, Il)',
 'Catwoman',
 'Laputa: Castle in the Sky (Tenkû no shiro Rapyuta)',
 "Madagascar 3: Europe's Most Wanted",
 'Gone with the Wind',
 'Richard III',
 'Man of Tai Chi',
 'Hitman: Agent 47',
 'Counselor, The',
 'Narcopolis',
 'Hangover Part III, The',
 'Prelude to a Kiss',
 'Perfect Score, The',
 'Julia',
 '8 1/2 (8½)',
 'I Sell the Dead',
 'Phantom of the Paradise',
 'Rent',
 'Fifth Element, The',
 'Greenberg',
 'Watch, The',
 "The Maid's Room",
 'Arrival, The',
 'Beowulf',
 'Captain Fantastic',
 'Cool Hand Luke',
 'Dick',
 "Man Bites Dog (C'est arrivé près de chez vous)",
 'About Last Night',
 'Life as We Know It',
 'Yards, The',
 'Mr. Woodcock',
 'Charlie Countryman',
 'Bad Company',
 'Instinct',
 'Sheena',
 'A-Team, The',
 'Koyaanisqatsi (a.k.a. Koyaanisqatsi: Life Out of Balance)',
 'Central Intelligence',
 'Alex Cross',
 'Harley Davidson and the Marlboro Man',
 'Medicine Man',
 'Semi-Pro',
 'Fast and the Furious, The',
 'Freejack',
 'Benny & Joon',
 'Nightmare Before Christmas, The',
 'Road to El Dorado, The',
 'Three Men and a Little Lady',
 'Eye for an Eye',
 'South Pacific',
 'Sudden Death',
 'Producers, The',
 'Secret Garden, The',
 'Careful What You Wish For',
 'Vanya on 42nd Street',
 'Mystic Pizza',
 'Eraserhead',
 'Witness for the Prosecution',
 "Weekend at Bernie's II",
 'Cutthroat Island',
 'Tears of the Sun',
 'Pirates of the Caribbean: On Stranger Tides',
 'Thin Blue Line, The',
 'Fast and the Furious: Tokyo Drift, The (Fast and the Furious 3, The)',
 'Harry and the Hendersons',
 'Juno',
 'Home Alone 2: Lost in New York',
 'My Science Project',
 'Without a Paddle',
 'L.A. Story',
 'Ride Along',
 'Go',
 'Snake Eyes',
 'Civil Action, A',
 'Campus Man',
 'Never Say Never Again',
 'Fly, The',
 'The Loft',
 'Maltese Falcon, The (a.k.a. Dangerous Female)',
 'Zulu',
 'Three Fugitives',
 'Grey, The',
 'All About Eve',
 'Insider, The',
 'Renaissance Man',
 'Maggie',
 'Project Almanac',
 'Manhattan',
 'The Lovers',
 'My Demon Lover',
 'Pacific Heights',
 'Dying of the Light',
 'E.T. the Extra-Terrestrial',
 'Craft, The',
 'Wicked Blood',
 'Airplane!',
 'Pan',
 'First Time, The',
 "Butcher's Wife, The",
 'Brake',
 'Sister Act',
 'Boogie Nights',
 'Victor Frankenstein',
 'Night at the Museum: Battle of the Smithsonian',
 "Cheech & Chong's The Corsican Brothers",
 "Antonia's Line (Antonia)",
 'Kite',
 'Nature Calls',
 'Grumpier Old Men',
 "Fool's Gold",
 'Dying Young',
 'Farewell My Concubine (Ba wang bie ji)',
 'Our Brand Is Crisis',
 'Men of Honor',
 'Stealing Harvard',
 'Surrogates',
 'Paradise Lost: The Child Murders at Robin Hood Hills',
 'Unbreakable',
 'Blood Simple',
 'Takers',
 'Forces of Nature',
 'Summer of Sam',
 'Payback',
 'Corky Romano',
 'Underworld',
 'Date with an Angel',
 'Allnighter, The',
 'Abraham Lincoln: Vampire Hunter',
 'Skulls, The',
 'I Am Sam',
 'Slums of Beverly Hills, The',
 'I Love You Phillip Morris',
 'It Could Happen to You',
 'Mary Poppins',
 'My Stepmother Is an Alien',
 'Happiness',
 'Life Less Ordinary, A',
 'The Perfect Guy',
 'Hot Tub Time Machine',
 'Deadfall',
 'Corrina, Corrina',
 'Romeo and Juliet',
 'Smokey and the Bandit II',
 'Jean de Florette',
 'RoboCop 3',
 'Best Exotic Marigold Hotel, The',
 'Nutty Professor, The',
 'Hairspray',
 'Welcome to the Jungle',
 'Bully',
 'Three to Tango',
 'Night at the Museum: Secret of the Tomb',
 'Bird on a Wire',
 "Charlie's Angels",
 'James and the Giant Peach',
 'Fantasia',
 'Catch .44',
 'Inspector Gadget',
 'War Room, The',
 'American Ultra',
 'Last Detail, The',
 'Beneath the Planet of the Apes',
 'Firefox',
 'All is Bright',
 'Notorious',
 'Airheads',
 'Courage Under Fire',
 'Cocoon: The Return',
 'Misery',
 'Transporter 2',
 'Flawless',
 'Woman in the Dunes (Suna no onna)',
 'Point Break',
 'Young Einstein',
 'Daddy Day Care',
 'Police Academy 2: Their First Assignment',
 "Cookie's Fortune",
 'Tango & Cash',
 "I Don't Know How She Does It",
 'Big Bang, The',
 'Ghosts of Girlfriends Past',
 'Iron Eagle II',
 'Hot Chick, The',
 'Beautiful Creatures',
 'Flushed Away',
 'Naked',
 'Total Recall',
 'Zipper',
 'Altered States',
 'Rio',
 'Friday After Next',
 'Milk Money',

In [109]:
finaloutputlist=finalmovielist[:8]

In [110]:
finaloutputlist

['Shawshank Redemption, The',
 'Forrest Gump',
 'Pulp Fiction',
 'Silence of the Lambs, The',
 'Braveheart',
 'Apollo 13',
 'Star Wars: Episode IV - A New Hope',
 "Schindler's List"]